// Canonical site origin — also set as "homepage" in package.json and used by
// scripts/generate-mix-pages.mjs for social previews.
export const SITE_URL = 'https://supervuoto.org';

export function mixShareUrl(id) {
  return `${SITE_URL}/mix/${id}/`;
}

// The crawlable detail page: /mix/<line>/<title>/. `path` is generated by
// scripts/parse-mixtapes.mjs; fall back to the share stub if it's missing.
export function mixPageUrl(entry) {
  return entry && entry.path
    ? `${SITE_URL}/mix/${entry.path}/`
    : mixShareUrl(entry && entry.id);
}
